
[ERROR] 2025-06-21 00:53:16,668 django.request - Internal Server Error: /admin/accounts/user/4/change/
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/admin/options.py", line 840, in get_form
    return modelform_factory(self.model, **defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/forms/models.py", line 654, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/forms/models.py", line 312, in __new__
    fields = fields_for_model(
             ^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/forms/models.py", line 207, in fields_for_model
    raise FieldError(
django.core.exceptions.FieldError: 'avatar' cannot be specified for User model form as it is a non-editable field

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/admin/options.py", line 719, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 246, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1987, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1840, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1878, in _changeform_view
    ModelForm = self.get_form(
                ^^^^^^^^^^^^^^
  File "/app/accounts/admin.py", line 33, in get_form
    form = super().get_form(request, obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/auth/admin.py", line 98, in get_form
    return super().get_form(request, obj, **defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/admin/options.py", line 842, in get_form
    raise FieldError(
django.core.exceptions.FieldError: 'avatar' cannot be specified for User model form as it is a non-editable field. Check fields/fieldsets/exclude attributes of class UserAdmin.
[ERROR] 2025-06-21 00:53:55,579 django.request - Internal Server Error: /admin/marketplace/media/add/
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/admin/options.py", line 840, in get_form
    return modelform_factory(self.model, **defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/forms/models.py", line 654, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/forms/models.py", line 312, in __new__
    fields = fields_for_model(
             ^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/forms/models.py", line 207, in fields_for_model
    raise FieldError(
django.core.exceptions.FieldError: 'created_at' cannot be specified for Media model form as it is a non-editable field

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/admin/options.py", line 719, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 246, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1984, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1840, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1878, in _changeform_view
    ModelForm = self.get_form(
                ^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/admin/options.py", line 842, in get_form
    raise FieldError(
django.core.exceptions.FieldError: 'created_at' cannot be specified for Media model form as it is a non-editable field. Check fields/fieldsets/exclude attributes of class MediaAdmin.
[ERROR] 2025-06-21 15:30:10,234 django.request - Internal Server Error: /api/marketplace/media/
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.NotNullViolation: null value in column "product_id" of relation "marketplace_media" violates not-null constraint
DETAIL:  Failing row contains (4, , null, null, 2025-06-21 15:30:09.838453+00, , f, ).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/marketplace/views.py", line 274, in create
    return super().create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/app/marketplace/views.py", line 278, in perform_create
    serializer.save()
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/serializers.py", line 210, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/serializers.py", line 991, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/query.py", line 663, in create
    obj.save(force_insert=True, using=self.db)
  File "/app/marketplace/models.py", line 110, in save
    super().save(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/base.py", line 902, in save
    self.save_base(
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/base.py", line 1008, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/base.py", line 1169, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/base.py", line 1210, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/query.py", line 1864, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1882, in execute_sql
    cursor.execute(sql, params)
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: null value in column "product_id" of relation "marketplace_media" violates not-null constraint
DETAIL:  Failing row contains (4, , null, null, 2025-06-21 15:30:09.838453+00, , f, ).

[ERROR] 2025-06-21 15:31:06,471 django.request - Internal Server Error: /api/marketplace/media/
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.NotNullViolation: null value in column "product_id" of relation "marketplace_media" violates not-null constraint
DETAIL:  Failing row contains (5, , null, null, 2025-06-21 15:31:06.367258+00, , f, ).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/marketplace/views.py", line 274, in create
    return super().create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/app/marketplace/views.py", line 278, in perform_create
    serializer.save()
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/serializers.py", line 210, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/serializers.py", line 991, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/query.py", line 663, in create
    obj.save(force_insert=True, using=self.db)
  File "/app/marketplace/models.py", line 110, in save
    super().save(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/base.py", line 902, in save
    self.save_base(
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/base.py", line 1008, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/base.py", line 1169, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/base.py", line 1210, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/query.py", line 1864, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1882, in execute_sql
    cursor.execute(sql, params)
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: null value in column "product_id" of relation "marketplace_media" violates not-null constraint
DETAIL:  Failing row contains (5, , null, null, 2025-06-21 15:31:06.367258+00, , f, ).

[ERROR] 2025-06-21 18:58:24,152 django.request - Internal Server Error: /api/payments/create-checkout-session/
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/payments/views.py", line 55, in post
    if not product.owner.stripe_account_id:
           ^^^^^^^^^^^^^
AttributeError: 'Product' object has no attribute 'owner'
[ERROR] 2025-06-21 19:02:16,874 django.request - Internal Server Error: /api/payments/create-checkout-session/
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/payments/views.py", line 55, in post
    if not product.owner.stripe_account_id:
           ^^^^^^^^^^^^^
AttributeError: 'Product' object has no attribute 'owner'
[ERROR] 2025-06-21 19:03:16,793 django.request - Internal Server Error: /api/payments/create-checkout-session/
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/payments/views.py", line 55, in post
    if not product.owner.stripe_account_id:
           ^^^^^^^^^^^^^
AttributeError: 'Product' object has no attribute 'owner'
[ERROR] 2025-06-21 19:16:57,673 django.request - Internal Server Error: /api/payments/create-checkout-session/
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/payments/views.py", line 55, in post
    if not product.owner.stripe_account_id:
           ^^^^^^^^^^^^^
AttributeError: 'Product' object has no attribute 'owner'
[ERROR] 2025-06-21 19:17:10,090 django.request - Internal Server Error: /api/payments/create-checkout-session/
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/payments/views.py", line 55, in post
    if not product.owner.stripe_account_id:
           ^^^^^^^^^^^^^
AttributeError: 'Product' object has no attribute 'owner'
[ERROR] 2025-06-21 19:17:16,395 django.request - Internal Server Error: /api/payments/create-checkout-session/
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/payments/views.py", line 55, in post
    if not product.owner.stripe_account_id:
           ^^^^^^^^^^^^^
AttributeError: 'Product' object has no attribute 'owner'
[ERROR] 2025-06-21 20:18:12,247 django.request - Internal Server Error: /api/payments/create-checkout-session/
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/payments/views.py", line 55, in post
    if not product.owner.stripe_account_id:
           ^^^^^^^^^^^^^
AttributeError: 'Product' object has no attribute 'owner'
[ERROR] 2025-06-21 20:18:22,047 django.request - Internal Server Error: /api/payments/create-checkout-session/
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/payments/views.py", line 55, in post
    if not product.owner.stripe_account_id:
           ^^^^^^^^^^^^^
AttributeError: 'Product' object has no attribute 'owner'
[ERROR] 2025-06-21 20:18:33,577 django.request - Internal Server Error: /api/payments/create-checkout-session/
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/payments/views.py", line 55, in post
    if not product.owner.stripe_account_id:
           ^^^^^^^^^^^^^
AttributeError: 'Product' object has no attribute 'owner'
[ERROR] 2025-06-21 20:18:44,861 django.request - Internal Server Error: /api/payments/create-checkout-session/
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/payments/views.py", line 55, in post
    if not product.owner.stripe_account_id:
           ^^^^^^^^^^^^^
AttributeError: 'Product' object has no attribute 'owner'
[ERROR] 2025-06-21 20:18:49,695 django.request - Internal Server Error: /api/payments/create-checkout-session/
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/payments/views.py", line 55, in post
    if not product.owner.stripe_account_id:
           ^^^^^^^^^^^^^
AttributeError: 'Product' object has no attribute 'owner'
[ERROR] 2025-06-21 20:18:56,862 django.request - Internal Server Error: /api/payments/create-checkout-session/
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/payments/views.py", line 55, in post
    if not product.owner.stripe_account_id:
           ^^^^^^^^^^^^^
AttributeError: 'Product' object has no attribute 'owner'
[ERROR] 2025-06-21 20:19:51,761 django.request - Internal Server Error: /api/payments/create-checkout-session/
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/payments/views.py", line 55, in post
    if not product.owner.stripe_account_id:
           ^^^^^^^^^^^^^
AttributeError: 'Product' object has no attribute 'owner'
[ERROR] 2025-06-21 20:20:24,575 django.request - Internal Server Error: /api/payments/create-checkout-session/
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/payments/views.py", line 55, in post
    if not product.owner.stripe_account_id:
           ^^^^^^^^^^^^^
AttributeError: 'Product' object has no attribute 'owner'
[ERROR] 2025-06-21 20:20:28,756 django.request - Internal Server Error: /api/payments/create-checkout-session/
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/payments/views.py", line 55, in post
    if not product.owner.stripe_account_id:
           ^^^^^^^^^^^^^
AttributeError: 'Product' object has no attribute 'owner'
[ERROR] 2025-06-21 20:20:37,294 django.request - Internal Server Error: /api/payments/create-checkout-session/
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/payments/views.py", line 55, in post
    if not product.owner.stripe_account_id:
           ^^^^^^^^^^^^^
AttributeError: 'Product' object has no attribute 'owner'
[ERROR] 2025-06-21 20:21:06,037 django.request - Internal Server Error: /api/payments/create-checkout-session/
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/payments/views.py", line 55, in post
    if not product.owner.stripe_account_id:
           ^^^^^^^^^^^^^
AttributeError: 'Product' object has no attribute 'owner'
[ERROR] 2025-06-21 20:22:18,974 django.request - Internal Server Error: /api/payments/create-checkout-session/
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/payments/views.py", line 55, in post
    if not product.owner.stripe_account_id:
           ^^^^^^^^^^^^^
AttributeError: 'Product' object has no attribute 'owner'
[ERROR] 2025-06-21 20:22:30,820 django.request - Internal Server Error: /api/payments/create-checkout-session/
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/payments/views.py", line 55, in post
    if not product.owner.stripe_account_id:
           ^^^^^^^^^^^^^
AttributeError: 'Product' object has no attribute 'owner'
[ERROR] 2025-06-21 20:32:28,044 django.request - Internal Server Error: /api/payments/create-checkout-session/
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/payments/views.py", line 55, in post
    if not product.owner.stripe_account_id:
           ^^^^^^^^^^^^^
AttributeError: 'Product' object has no attribute 'owner'
[ERROR] 2025-06-21 20:43:51,846 django.request - Internal Server Error: /api/payments/create-checkout-session/
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/payments/views.py", line 55, in post
    if not product.owner.stripe_account_id:
           ^^^^^^^^^^^^^
AttributeError: 'Product' object has no attribute 'owner'
[ERROR] 2025-06-21 21:04:14,467 payments.views - Error creating checkout session: 'Settings' object has no attribute 'FRONTEND_URL'
[ERROR] 2025-06-21 21:04:14,511 django.request - Internal Server Error: /api/payments/create-checkout-session/
[ERROR] 2025-06-21 21:04:26,575 payments.views - Error creating checkout session: 'Settings' object has no attribute 'FRONTEND_URL'
[ERROR] 2025-06-21 21:04:26,586 django.request - Internal Server Error: /api/payments/create-checkout-session/
[ERROR] 2025-06-21 21:14:17,819 payments.views - Error creating checkout session: Request req_MYZe7KBWkNcsOj: Your destination account needs to have at least one of the following capabilities enabled: transfers, crypto_transfers, legacy_payments
[ERROR] 2025-06-21 21:14:17,825 django.request - Internal Server Error: /api/payments/create-checkout-session/
[ERROR] 2025-06-21 22:26:40,615 django.request - Internal Server Error: /api/marketplace/media/
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.NotNullViolation: null value in column "product_id" of relation "marketplace_media" violates not-null constraint
DETAIL:  Failing row contains (2, , null, null, 2025-06-21 22:26:40.501582+00, , f, ).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/marketplace/views.py", line 278, in create
    return super().create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/app/marketplace/views.py", line 282, in perform_create
    serializer.save()
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/serializers.py", line 210, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/serializers.py", line 991, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/query.py", line 663, in create
    obj.save(force_insert=True, using=self.db)
  File "/app/marketplace/models.py", line 110, in save
    super().save(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/base.py", line 902, in save
    self.save_base(
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/base.py", line 1008, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/base.py", line 1169, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/base.py", line 1210, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/query.py", line 1864, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1882, in execute_sql
    cursor.execute(sql, params)
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: null value in column "product_id" of relation "marketplace_media" violates not-null constraint
DETAIL:  Failing row contains (2, , null, null, 2025-06-21 22:26:40.501582+00, , f, ).

[ERROR] 2025-06-22 12:56:03,733 django.request - Internal Server Error: /api/storage/upload/
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2128, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'undefined'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/storage/views.py", line 40, in post
    product = Product.objects.get(id=product_id, seller=request.user)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/query.py", line 619, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/query.py", line 1491, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/query.py", line 1509, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/query.py", line 1516, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1643, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1675, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1585, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1412, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/lookups.py", line 38, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/lookups.py", line 410, in get_prep_lookup
    return super().get_prep_lookup()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/lookups.py", line 96, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2130, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'undefined'.
[ERROR] 2025-06-22 14:01:07,924 marketplace.views - perform_create: Error checking product count for user yibegis665@calorpg.com: Você atingiu o limite máximo de 10 produtos.
[ERROR] 2025-06-22 15:28:32,317 django.request - Internal Server Error: /admin/
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/sessions/backends/base.py", line 244, in _get_session
    return self._session_cache
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 265, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 234, in inner
    if not self.has_permission(request):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 207, in has_permission
    return request.user.is_active and request.user.is_staff
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/utils/functional.py", line 251, in inner
    self._setup()
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/utils/functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/auth/middleware.py", line 39, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/auth/middleware.py", line 19, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/auth/__init__.py", line 304, in get_user
    user_id = _get_user_session_key(request)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/auth/__init__.py", line 95, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
                                               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/sessions/backends/base.py", line 55, in __getitem__
    return self._session[key]
           ^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/sessions/backends/base.py", line 249, in _get_session
    self._session_cache = self.load()
                          ^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/sessions/backends/db.py", line 55, in load
    s = self._get_session_from_db()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/sessions/backends/db.py", line 34, in _get_session_from_db
    return self.model.objects.get(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/query.py", line 1945, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^

[ERROR] 2025-06-22 15:29:15,220 django.request - Internal Server Error: /admin/
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/sessions/backends/base.py", line 244, in _get_session
    return self._session_cache
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 265, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 234, in inner
    if not self.has_permission(request):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 207, in has_permission
    return request.user.is_active and request.user.is_staff
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/utils/functional.py", line 251, in inner
    self._setup()
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/utils/functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/auth/middleware.py", line 39, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/auth/middleware.py", line 19, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/auth/__init__.py", line 304, in get_user
    user_id = _get_user_session_key(request)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/auth/__init__.py", line 95, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
                                               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/sessions/backends/base.py", line 55, in __getitem__
    return self._session[key]
           ^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/sessions/backends/base.py", line 249, in _get_session
    self._session_cache = self.load()
                          ^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/sessions/backends/db.py", line 55, in load
    s = self._get_session_from_db()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/sessions/backends/db.py", line 34, in _get_session_from_db
    return self.model.objects.get(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/query.py", line 1945, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^

[ERROR] 2025-06-22 15:30:58,537 django.request - Internal Server Error: /admin/
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/sessions/backends/base.py", line 244, in _get_session
    return self._session_cache
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 265, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 234, in inner
    if not self.has_permission(request):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 207, in has_permission
    return request.user.is_active and request.user.is_staff
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/utils/functional.py", line 251, in inner
    self._setup()
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/utils/functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/auth/middleware.py", line 39, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/auth/middleware.py", line 19, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/auth/__init__.py", line 304, in get_user
    user_id = _get_user_session_key(request)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/auth/__init__.py", line 95, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
                                               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/sessions/backends/base.py", line 55, in __getitem__
    return self._session[key]
           ^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/sessions/backends/base.py", line 249, in _get_session
    self._session_cache = self.load()
                          ^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/sessions/backends/db.py", line 55, in load
    s = self._get_session_from_db()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/sessions/backends/db.py", line 34, in _get_session_from_db
    return self.model.objects.get(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/query.py", line 1945, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^

[ERROR] 2025-06-22 15:31:11,674 django.request - Internal Server Error: /admin/
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/sessions/backends/base.py", line 244, in _get_session
    return self._session_cache
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 265, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 234, in inner
    if not self.has_permission(request):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 207, in has_permission
    return request.user.is_active and request.user.is_staff
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/utils/functional.py", line 251, in inner
    self._setup()
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/utils/functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/auth/middleware.py", line 39, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/auth/middleware.py", line 19, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/auth/__init__.py", line 304, in get_user
    user_id = _get_user_session_key(request)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/auth/__init__.py", line 95, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
                                               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/sessions/backends/base.py", line 55, in __getitem__
    return self._session[key]
           ^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/sessions/backends/base.py", line 249, in _get_session
    self._session_cache = self.load()
                          ^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/sessions/backends/db.py", line 55, in load
    s = self._get_session_from_db()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/sessions/backends/db.py", line 34, in _get_session_from_db
    return self.model.objects.get(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/query.py", line 1945, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^

[ERROR] 2025-06-22 15:55:07,599 django.request - Internal Server Error: /admin/
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/sessions/backends/base.py", line 244, in _get_session
    return self._session_cache
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 265, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 234, in inner
    if not self.has_permission(request):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 207, in has_permission
    return request.user.is_active and request.user.is_staff
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/utils/functional.py", line 251, in inner
    self._setup()
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/utils/functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/auth/middleware.py", line 39, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/auth/middleware.py", line 19, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/auth/__init__.py", line 304, in get_user
    user_id = _get_user_session_key(request)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/auth/__init__.py", line 95, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
                                               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/sessions/backends/base.py", line 55, in __getitem__
    return self._session[key]
           ^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/sessions/backends/base.py", line 249, in _get_session
    self._session_cache = self.load()
                          ^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/sessions/backends/db.py", line 55, in load
    s = self._get_session_from_db()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/sessions/backends/db.py", line 34, in _get_session_from_db
    return self.model.objects.get(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/query.py", line 1945, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^

[ERROR] 2025-06-22 15:55:08,404 django.request - Internal Server Error: /admin/
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/sessions/backends/base.py", line 244, in _get_session
    return self._session_cache
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 265, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 234, in inner
    if not self.has_permission(request):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 207, in has_permission
    return request.user.is_active and request.user.is_staff
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/utils/functional.py", line 251, in inner
    self._setup()
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/utils/functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/auth/middleware.py", line 39, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/auth/middleware.py", line 19, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/auth/__init__.py", line 304, in get_user
    user_id = _get_user_session_key(request)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/auth/__init__.py", line 95, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
                                               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/sessions/backends/base.py", line 55, in __getitem__
    return self._session[key]
           ^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/sessions/backends/base.py", line 249, in _get_session
    self._session_cache = self.load()
                          ^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/sessions/backends/db.py", line 55, in load
    s = self._get_session_from_db()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/sessions/backends/db.py", line 34, in _get_session_from_db
    return self.model.objects.get(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/query.py", line 1945, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^

[ERROR] 2025-06-22 15:55:22,581 django.request - Internal Server Error: /admin/
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/sessions/backends/base.py", line 244, in _get_session
    return self._session_cache
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 265, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 234, in inner
    if not self.has_permission(request):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 207, in has_permission
    return request.user.is_active and request.user.is_staff
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/utils/functional.py", line 251, in inner
    self._setup()
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/utils/functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/auth/middleware.py", line 39, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/auth/middleware.py", line 19, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/auth/__init__.py", line 304, in get_user
    user_id = _get_user_session_key(request)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/auth/__init__.py", line 95, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
                                               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/sessions/backends/base.py", line 55, in __getitem__
    return self._session[key]
           ^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/sessions/backends/base.py", line 249, in _get_session
    self._session_cache = self.load()
                          ^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/sessions/backends/db.py", line 55, in load
    s = self._get_session_from_db()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/contrib/sessions/backends/db.py", line 34, in _get_session_from_db
    return self.model.objects.get(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/query.py", line 1945, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.cache/pypoetry/virtualenvs/codebay-final-project-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^

[ERROR] 2025-06-22 20:40:06,940 marketplace.views - perform_create: Error checking product count for user vepew90172@ihnpo.com: Você atingiu o limite máximo de 10 produtos.
